= dbt

== Links
https://docs.getdbt.com/tutorial/setting-up/[Tutorial] +
https://medium.com/the-telegraph-engineering/dbt-a-new-way-to-handle-data-transformation-at-the-telegraph-868ce3964eb4[Introduction] +

== Commands
 cd ~/Documents/workspaces/python
 python3 -m venv /home/edittrich/Documents/workspaces/python/venv/dbt --copies --prompt dbt
 source /home/edittrich/Documents/workspaces/python/venv/dbt/bin/activate
 pip install dbt
 pip freeze > requirements.txt

 git clone git@github.com:edittrich/dbt.git
 cd dbt
 touch README.adoc
 git add README.adoc
 git commit -m "Initial"
 git push -u origin master

 dbt init jaffle-shop
 cd jaffle_shop
 cat > /home/edittrich/.dbt/profiles.yml << "EOF" 
 jaffle_shop: # Needs to match to the profile in the dbt_project.yml
   target: dev
   outputs:
     dev:
       type: bigquery
       method: service-account
       keyfile: /home/edittrich/.ssh/dbt-user@dev1-onb-playground-18fd.json # Replace with the full path to the keyfile
       project: dev1-onb-playground-18fd # Replace with the GCP project id
       dataset: dbt_spike # Replace with the BigQuery dataset 
       threads: 1
       timeout_seconds: 300
       location: europe-west3
       priority: interactive
 
 EOF
  
 dbt debug
 dbt run
 deactivate
